nelmio_api_doc:
    documentation:
        info:
            title: Test app for microservices
            description: This is an app to add all needed features for a php microservice!
            version: 0.1.0
    routes:
        path_patterns:
            - ^/api(?!/doc$)
