services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    App\Repository\TestUserRepository:
        factory: ['@doctrine','getRepository']
        arguments: ['App\Entity\TestUser']
        public: true
